openapi: "3.0.0"
info:
  version: 1.0.0
  title: zhurd
  license:
    name: Apache 2.0
servers:
  - url: http://localhost:3003/v1
paths:

  /printers:
    get:
      summary: List all printers
      operationId: listPrinters
      tags:
        - printers
      responses:
        200:
          description: An paged array of printers
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Printers"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a printer
      operationId: createPrinter
      tags:
        - printers
      responses:
        201:
          description: created printer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreatePrinter"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /printers/{printerId}:
    get:
      summary: Info for a specific printer
      operationId: showPrinterById
      tags:
        - printers
      parameters:
        - name: printerId
          in: path
          required: true
          description: The id of the printer to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Printer"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: delete a specific printer
      operationId: deletePrinterById
      tags:
        - printers
      parameters:
        - name: printerId
          in: path
          required: true
          description: The id of the printer to delete
          schema:
            type: string
      responses:
        204:
          description: No content
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /labels:
    get:
      summary: List all labels
      operationId: listLabels
      tags:
        - labels
      responses:
        200:
          description: An paged array of lables
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Labels"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a label
      operationId: createLabel
      tags:
        - labels
      responses:
        201:
          description: created label
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateLabel"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /labels/{labelId}:
    get:
      summary: Info for a specific label
      operationId: showLabelById
      tags:
        - labels
      parameters:
        - name: labelId
          in: path
          required: true
          description: The id of the label to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Label"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: delete a specific label
      operationId: deleteLabelById
      tags:
        - labels
      parameters:
        - name: labelId
          in: path
          required: true
          description: The id of the label to delete
          schema:
            type: string
      responses:
        204:
          description: No content
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /labels/{labelId}/templates:
    get:
      summary: List all tamplates
      operationId: listTemplates
      tags:
        - templates
      parameters:
        - name: labelId
          in: path
          required: true
          description: The id of the label
          schema:
            type: string
      responses:
        200:
          description: An paged array of templates
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Templates"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a template
      operationId: createTemplate
      tags:
        - templates
      parameters:
        - name: labelId
          in: path
          required: true
          description: The id of the label
          schema:
            type: string
      responses:
        201:
          description: created template
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateTemplate"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /labels/{labelId}/templates/{templateId}:
    get:
      summary: Info for a specific template
      operationId: showTemplateById
      tags:
        - templates
      parameters:
        - name: labelId
          in: path
          required: true
          description: The id of the label
          schema:
            type: string
        - name: templateId
          in: path
          required: true
          description: The id of the template to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Template"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      summary: delete a specific template
      operationId: deleteTemplateById
      tags:
        - templates
      parameters:
        - name: labelId
          in: path
          required: true
          description: The id of the label
          schema:
            type: string
        - name: templateId
          in: path
          required: true
          description: The id of the template to delete
          schema:
            type: string
      responses:
        204:
          description: No content
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    CreatePrinter:
      required:
        - addr
        - type
      properties:
        addr:
          type: string
          example: "192.168.0.1:7777"
        type:
          type: string
          example: "ZPL"
        comment:
          type: string
    Printer:
      required:
        - id
        - addr
        - type
      properties:
        id:
          type: integer
          format: int64
        addr:
          type: string
          example: "192.168.0.1:7777"
        type:
          type: string
          example: "ZPL"
        comment:
          type: string
    Printers:
      type: array
      items:
        $ref: "#/components/schemas/Printer"
    CreateLabel:
      required:
        - name
      properties:
        name:
          type: string
          example: "label1"
        comment:
          type: string
    Label:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: "label1"
        comment:
          type: string
    Labels:
      type: array
      items:
        $ref: "#/components/schemas/Label"
    CreateTemplate:
      required:
        - type
        - body
      properties:
        type:
          type: string
          example: "ZPL"
        body:
          type: string
    Template:
      required:
        - id
        - type
        - body
      properties:
        id:
          type: integer
          format: int64
        type:
          type: string
          example: "ZPL"
        body:
          type: string
    Templates:
      type: array
      items:
        $ref: "#/components/schemas/Template"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

