services:
  zhurd:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - migrator

  db:
    image: postgres:17.2
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=zhurd
      - POSTGRES_DB=zhurd
      - POSTGRES_PASSWORD=passwordsecretdb
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -h localhost -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5

  migrator:
    build: 
      context: .
      dockerfile: ./dbmigrations/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./dbmigrations:/dbmigrations/
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_MIGRATION_DIR: ./dbmigrations
      GOOSE_DBSTRING: "postgres://zhurd:passwordsecretdb@db:5432/zhurd?sslmode=disable"

volumes:
  db-data:
